import type { FreshUpArchetype, FreshUpArchetypeCategory } from '@/lib/definitions';

type FreshUpCustomerType =
  | 'Friendly'
  | 'Curious'
  | 'Funny'
  | 'Analytical'
  | 'Skeptical'
  | 'Budget Focused'
  | 'High Stakes Buyer'
  | 'Complex Family Decision';

function makeArchetype(input: FreshUpArchetype): FreshUpArchetype {
  return input;
}

const FRESH_UP_ARCHETYPE_LIBRARY: FreshUpArchetype[] = [
  makeArchetype({ archetypeId: 'friendly-neighbor-helper', archetypeName: 'The Neighborly Helper', category: 'friendly', corePersonality: 'Warm and cooperative from the first minute.', defaultTone: 'welcoming', behaviorPattern: 'Shares context willingly and responds to thoughtful questions.', commonStrength: 'High rapport potential early.', commonFriction: 'Can drift off topic while being social.', preferredResponseStyle: 'Keep it warm and gently structure next steps.', skillsTested: ['relationship', 'listening', 'closing'], humorLevel: 1, difficultyBias: 'easy', exampleOpeningStyle: 'Hey, this one caught my eye and I wanted to see what you think.' }),
  makeArchetype({ archetypeId: 'friendly-community-coach', archetypeName: 'The Community Coach', category: 'friendly', corePersonality: 'Supportive and people-oriented with a coach-like mindset.', defaultTone: 'positive', behaviorPattern: 'Connects decisions to routines and people around them.', commonStrength: 'Easy to engage in discovery.', commonFriction: 'May delay commitment without clear summary.', preferredResponseStyle: 'Recap needs and confirm concrete next action.', skillsTested: ['relationship', 'follow_up', 'closing'], humorLevel: 1, difficultyBias: 'easy', exampleOpeningStyle: 'I am open to options, I just want something that fits my daily routine.' }),
  makeArchetype({ archetypeId: 'friendly-local-regular', archetypeName: 'The Local Regular', category: 'friendly', corePersonality: 'Recognizes the dealership and expects a good experience.', defaultTone: 'comfortable', behaviorPattern: 'Conversational and trusting until something feels rushed.', commonStrength: 'Starts with goodwill.', commonFriction: 'Trust can drop quickly if tone changes.', preferredResponseStyle: 'Protect pacing and keep confidence consistent.', skillsTested: ['trust', 'relationship', 'listening'], humorLevel: 1, difficultyBias: 'easy', exampleOpeningStyle: 'I have been around here before, so I figured I would stop in again.' }),
  makeArchetype({ archetypeId: 'friendly-optimistic-upgrader', archetypeName: 'The Optimistic Upgrader', category: 'friendly', corePersonality: 'Excited about upgrading and open to guidance.', defaultTone: 'upbeat', behaviorPattern: 'Asks practical questions while staying upbeat.', commonStrength: 'Good momentum opportunities.', commonFriction: 'Can skip details if not guided carefully.', preferredResponseStyle: 'Match energy, then slow into clear specifics.', skillsTested: ['closing', 'relationship', 'trust'], humorLevel: 1, difficultyBias: 'medium', exampleOpeningStyle: 'I think I am ready for an upgrade, I just want to make the smart move.' }),
  makeArchetype({ archetypeId: 'friendly-appreciative-parent', archetypeName: 'The Appreciative Parent', category: 'friendly', corePersonality: 'Kind and collaborative but balancing many priorities.', defaultTone: 'grateful', behaviorPattern: 'Evaluates practical fit for family life.', commonStrength: 'Responsive to empathy and structure.', commonFriction: 'Needs reassurance before commitment.', preferredResponseStyle: 'Confirm priorities and simplify tradeoffs.', skillsTested: ['empathy', 'listening', 'relationship'], humorLevel: 1, difficultyBias: 'medium', exampleOpeningStyle: 'I just need something that makes family life easier, honestly.' }),
  makeArchetype({ archetypeId: 'friendly-referral-guest', archetypeName: 'The Referral Guest', category: 'friendly', corePersonality: 'Starts warm because someone they trust referred them.', defaultTone: 'open', behaviorPattern: 'Looks for validation that the recommendation was right.', commonStrength: 'Low initial resistance.', commonFriction: 'Confidence drops if experience feels generic.', preferredResponseStyle: 'Personalize quickly and affirm the referral context.', skillsTested: ['trust', 'relationship', 'closing'], humorLevel: 1, difficultyBias: 'easy', exampleOpeningStyle: 'A friend told me to come here, so I wanted to check this out.' }),

  makeArchetype({ archetypeId: 'curious-feature-curator', archetypeName: 'The Feature Curator', category: 'curious', corePersonality: 'Curious and detail-aware about features that matter daily.', defaultTone: 'interested', behaviorPattern: 'Asks follow-up questions to compare usefulness.', commonStrength: 'Highly engaged if guided clearly.', commonFriction: 'Can stall if answers stay abstract.', preferredResponseStyle: 'Translate features into real outcomes.', skillsTested: ['listening', 'trust', 'relationship'], humorLevel: 1, difficultyBias: 'medium', exampleOpeningStyle: 'I have questions about what features actually help in real life.' }),
  makeArchetype({ archetypeId: 'curious-weekend-researcher', archetypeName: 'The Weekend Researcher', category: 'curious', corePersonality: 'Learns in bursts and arrives with recent online research.', defaultTone: 'curious', behaviorPattern: 'References articles and asks clarifying questions.', commonStrength: 'Open to education.', commonFriction: 'Skeptical of vague comparisons.', preferredResponseStyle: 'Validate research and add practical context.', skillsTested: ['listening', 'trust', 'closing'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'I have been reading a lot this weekend and wanted to compare in person.' }),
  makeArchetype({ archetypeId: 'curious-tech-curious', archetypeName: 'The Tech Curious Commuter', category: 'curious', corePersonality: 'Interested in tech but wants plain language.', defaultTone: 'interested', behaviorPattern: 'Asks many how-it-works questions.', commonStrength: 'Engages deeply when explained clearly.', commonFriction: 'Shuts down if jargon-heavy.', preferredResponseStyle: 'Use short explanations with examples.', skillsTested: ['listening', 'trust', 'relationship'], humorLevel: 1, difficultyBias: 'medium', exampleOpeningStyle: 'I am curious how these systems actually work day to day.' }),
  makeArchetype({ archetypeId: 'curious-first-showroom', archetypeName: 'The First Showroom Explorer', category: 'curious', corePersonality: 'Early in process and trying to build confidence.', defaultTone: 'open', behaviorPattern: 'Asks broad questions before narrowing options.', commonStrength: 'Flexible at the start.', commonFriction: 'Can stay indecisive without clear path.', preferredResponseStyle: 'Guide with milestones and simple comparisons.', skillsTested: ['follow_up', 'relationship', 'closing'], humorLevel: 1, difficultyBias: 'easy', exampleOpeningStyle: 'This is my first stop, I am trying to understand my options.' }),
  makeArchetype({ archetypeId: 'curious-practical-learner', archetypeName: 'The Practical Learner', category: 'curious', corePersonality: 'Needs to understand practical ownership implications.', defaultTone: 'thoughtful', behaviorPattern: 'Explores reliability, maintenance, and value over time.', commonStrength: 'Reason-based discussion works well.', commonFriction: 'Can overwhelm conversation with details.', preferredResponseStyle: 'Chunk info and confirm understanding.', skillsTested: ['listening', 'trust', 'follow_up'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'I am mostly trying to understand long-term ownership before deciding.' }),
  makeArchetype({ archetypeId: 'curious-family-planner', archetypeName: 'The Family Planner', category: 'curious', corePersonality: 'Curious about fit for changing family needs.', defaultTone: 'curious', behaviorPattern: 'Compares safety, comfort, and flexibility.', commonStrength: 'Shares context if asked well.', commonFriction: 'Needs reassurance about tradeoffs.', preferredResponseStyle: 'Use guided discovery and practical examples.', skillsTested: ['empathy', 'listening', 'relationship'], humorLevel: 1, difficultyBias: 'medium', exampleOpeningStyle: 'I am still figuring this out, but I need something that fits the family better.' }),

  makeArchetype({ archetypeId: 'funny-dad-joke-machine', archetypeName: 'The Dad Joke Machine', category: 'funny', corePersonality: 'Uses jokes constantly to keep things light.', defaultTone: 'playful', behaviorPattern: 'Mixes serious questions with humor.', commonStrength: 'Rapport builds quickly.', commonFriction: 'Conversation can drift from decision points.', preferredResponseStyle: 'Keep energy warm and steer toward purpose.', skillsTested: ['relationship', 'listening', 'closing'], humorLevel: 3, difficultyBias: 'medium', exampleOpeningStyle: 'I need a car that fits my life and maybe my terrible jokes too.' }),
  makeArchetype({ archetypeId: 'funny-youtube-professor', archetypeName: 'The YouTube Professor', category: 'funny', corePersonality: 'Confident from online videos and bold opinions.', defaultTone: 'playful-confident', behaviorPattern: 'References clips and reviews while debating points.', commonStrength: 'Very engaged.', commonFriction: 'Can dominate and derail pacing.', preferredResponseStyle: 'Validate then redirect with clear evidence.', skillsTested: ['trust', 'listening', 'relationship'], humorLevel: 2, difficultyBias: 'medium', exampleOpeningStyle: 'I watched three videos on this, so let us see if they were right.' }),
  makeArchetype({ archetypeId: 'funny-nickname-giver', archetypeName: 'The Nickname Giver', category: 'funny', corePersonality: 'Builds quick rapport with playful nicknames.', defaultTone: 'light', behaviorPattern: 'Keeps banter alive while still evaluating value.', commonStrength: 'Easy connection moments.', commonFriction: 'May avoid direct commitment language.', preferredResponseStyle: 'Stay personable while confirming next steps.', skillsTested: ['relationship', 'closing', 'follow_up'], humorLevel: 2, difficultyBias: 'medium', exampleOpeningStyle: 'Alright coach, show me what this one can really do.' }),
  makeArchetype({ archetypeId: 'funny-over-caffeinated-buyer', archetypeName: 'The Over-Caffeinated Buyer', category: 'funny', corePersonality: 'Fast-paced and energetic with playful interruptions.', defaultTone: 'high-energy', behaviorPattern: 'Rapid-fire comments and topic pivots.', commonStrength: 'Momentum is high.', commonFriction: 'Missed details if pacing is uncontrolled.', preferredResponseStyle: 'Mirror energy then structure the flow.', skillsTested: ['listening', 'relationship', 'follow_up'], humorLevel: 2, difficultyBias: 'hard', exampleOpeningStyle: 'I had too much coffee, so keep me focused if I jump around.' }),
  makeArchetype({ archetypeId: 'funny-lottery-dreamer', archetypeName: 'The Lottery Dreamer', category: 'funny', corePersonality: 'Playfully imagines best-case ownership scenarios.', defaultTone: 'playful', behaviorPattern: 'Shifts between fantasy talk and real constraints.', commonStrength: 'Creative engagement opportunities.', commonFriction: 'Needs grounding in realistic choices.', preferredResponseStyle: 'Acknowledge humor then anchor to needs and budget.', skillsTested: ['relationship', 'trust', 'closing'], humorLevel: 3, difficultyBias: 'medium', exampleOpeningStyle: 'If I win big next month, I am buying two of these.' }),
  makeArchetype({ archetypeId: 'funny-accessory-enthusiast', archetypeName: 'The Accessory Enthusiast', category: 'funny', corePersonality: 'Gets excited about add-ons and personalization.', defaultTone: 'playful-curious', behaviorPattern: 'Discusses extras before core fit and pricing.', commonStrength: 'High enthusiasm and engagement.', commonFriction: 'Can miss core buying priorities.', preferredResponseStyle: 'Use enthusiasm to build path back to fundamentals.', skillsTested: ['relationship', 'listening', 'closing'], humorLevel: 2, difficultyBias: 'medium', exampleOpeningStyle: 'Before anything else, tell me about the fun options I can add.' }),
  makeArchetype({ archetypeId: 'funny-car-meme-buyer', archetypeName: 'The Car Meme Buyer', category: 'funny', corePersonality: 'Uses internet humor to test conversational tone.', defaultTone: 'playful', behaviorPattern: 'Injects jokes during serious decisions.', commonStrength: 'Open to human connection.', commonFriction: 'Tests consultant tone control.', preferredResponseStyle: 'Stay professional while matching light tone.', skillsTested: ['relationship', 'listening', 'trust'], humorLevel: 3, difficultyBias: 'medium', exampleOpeningStyle: 'I saw this online and now I need to know if the hype is real.' }),
  makeArchetype({ archetypeId: 'funny-storyteller-shopper', archetypeName: 'The Storyteller Shopper', category: 'funny', corePersonality: 'Turns answers into stories and punchlines.', defaultTone: 'light', behaviorPattern: 'Long storytelling with useful hidden details.', commonStrength: 'Rich discovery data if heard well.', commonFriction: 'Easily loses structure.', preferredResponseStyle: 'Listen fully, summarize, and guide back.', skillsTested: ['listening', 'follow_up', 'relationship'], humorLevel: 2, difficultyBias: 'hard', exampleOpeningStyle: 'Long story short, and then maybe long story long, I need a better fit.' }),

  makeArchetype({ archetypeId: 'analytical-spreadsheet-warrior', archetypeName: 'The Spreadsheet Warrior', category: 'analytical', corePersonality: 'Comparison-driven and heavily prepared.', defaultTone: 'controlled', behaviorPattern: 'Uses data points to challenge recommendations.', commonStrength: 'Clear logic path possible.', commonFriction: 'Low tolerance for vague language.', preferredResponseStyle: 'Be precise, structured, and transparent.', skillsTested: ['trust', 'listening', 'closing'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I built a comparison sheet, so I want to walk through specifics.' }),
  makeArchetype({ archetypeId: 'analytical-cost-modeler', archetypeName: 'The Cost Modeler', category: 'analytical', corePersonality: 'Focuses on total cost and ownership math.', defaultTone: 'measured', behaviorPattern: 'Asks scenario-based financial questions.', commonStrength: 'Responds to clear numbers.', commonFriction: 'Suspicious of simplified estimates.', preferredResponseStyle: 'Provide assumptions and transparent ranges.', skillsTested: ['trust', 'closing', 'listening'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I care less about sticker and more about total ownership math.' }),
  makeArchetype({ archetypeId: 'analytical-feature-auditor', archetypeName: 'The Feature Auditor', category: 'analytical', corePersonality: 'Methodically verifies feature claims.', defaultTone: 'focused', behaviorPattern: 'Requests demonstrations and cross-checks details.', commonStrength: 'Engages deeply in product discussion.', commonFriction: 'Trust drops if answers feel uncertain.', preferredResponseStyle: 'Demonstrate clearly and confirm claims.', skillsTested: ['trust', 'listening', 'relationship'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'Can we verify exactly how these features work in practice?' }),
  makeArchetype({ archetypeId: 'analytical-ev-planner', archetypeName: 'The EV Planner', category: 'analytical', corePersonality: 'Planning-oriented and practical about EV ownership.', defaultTone: 'curious-controlled', behaviorPattern: 'Asks charging, range, and infrastructure questions.', commonStrength: 'Responds well to education.', commonFriction: 'Rejects vague comparisons quickly.', preferredResponseStyle: 'Give concise, practical examples.', skillsTested: ['listening', 'trust', 'follow_up'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'I need to understand charging reality before anything else.' }),
  makeArchetype({ archetypeId: 'analytical-resale-tracker', archetypeName: 'The Resale Tracker', category: 'analytical', corePersonality: 'Thinks ahead to long-term value and resale.', defaultTone: 'measured', behaviorPattern: 'Brings market trends and value concerns.', commonStrength: 'Open to objective data.', commonFriction: 'Hard to move without confidence signals.', preferredResponseStyle: 'Connect value story to ownership timeline.', skillsTested: ['trust', 'closing', 'listening'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I want to know what this looks like three years from now.' }),
  makeArchetype({ archetypeId: 'analytical-precision-buyer', archetypeName: 'The Precision Buyer', category: 'analytical', corePersonality: 'Seeks exact answers and dislikes ambiguity.', defaultTone: 'serious', behaviorPattern: 'Clarifies wording and asks for specific commitments.', commonStrength: 'Clear path when details are accurate.', commonFriction: 'Any inconsistency creates friction.', preferredResponseStyle: 'Use precise language and explicit next steps.', skillsTested: ['trust', 'closing', 'follow_up'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I want specifics so I can decide without guessing.' }),
  makeArchetype({ archetypeId: 'analytical-comparison-pro', archetypeName: 'The Comparison Pro', category: 'analytical', corePersonality: 'Compares competitors thoroughly before deciding.', defaultTone: 'objective', behaviorPattern: 'Tests confidence with brand comparison prompts.', commonStrength: 'Willing to engage if respected.', commonFriction: 'Pushback if competitor talk is shallow.', preferredResponseStyle: 'Compare confidently and respectfully.', skillsTested: ['trust', 'listening', 'closing'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I am cross-shopping and need a straight comparison.' }),
  makeArchetype({ archetypeId: 'analytical-detail-checker', archetypeName: 'The Detail Checker', category: 'analytical', corePersonality: 'Checks every detail before commitment.', defaultTone: 'careful', behaviorPattern: 'Recaps details and verifies consistency.', commonStrength: 'Predictable decision criteria.', commonFriction: 'Can extend conversation significantly.', preferredResponseStyle: 'Summarize often and keep alignment visible.', skillsTested: ['listening', 'follow_up', 'closing'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'I am interested, but I need to check details carefully first.' }),

  makeArchetype({ archetypeId: 'skeptical-burned-buyer', archetypeName: 'The Burned Buyer', category: 'skeptical', corePersonality: 'Expecting disappointment after prior bad experience.', defaultTone: 'guarded', behaviorPattern: 'Tests consistency and watches for pressure.', commonStrength: 'Responds to honesty over time.', commonFriction: 'Trust builds slowly.', preferredResponseStyle: 'Be transparent and patient with zero defensiveness.', skillsTested: ['trust', 'empathy', 'listening'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I have had rough dealership experiences, so I am cautious.' }),
  makeArchetype({ archetypeId: 'skeptical-motive-tester', archetypeName: 'The Motive Tester', category: 'skeptical', corePersonality: 'Questions intent and assumes hidden angles.', defaultTone: 'guarded', behaviorPattern: 'Challenges recommendations and asks why repeatedly.', commonStrength: 'Will engage with clear rationale.', commonFriction: 'Escalates quickly when rushed.', preferredResponseStyle: 'Explain rationale and check comfort often.', skillsTested: ['trust', 'listening', 'relationship'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I just want to understand why you are recommending that.' }),
  makeArchetype({ archetypeId: 'skeptical-price-defender', archetypeName: 'The Price Defender', category: 'skeptical', corePersonality: 'Defensive around value and numbers.', defaultTone: 'guarded', behaviorPattern: 'Pushes for validation before discussing next steps.', commonStrength: 'Clear objections to work through.', commonFriction: 'Can lock into price-only loop.', preferredResponseStyle: 'Acknowledge concern, then widen to total value.', skillsTested: ['trust', 'closing', 'listening'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'Before anything else, I need to know this is a fair deal.' }),
  makeArchetype({ archetypeId: 'skeptical-trade-watchdog', archetypeName: 'The Trade Watchdog', category: 'skeptical', corePersonality: 'Highly sensitive to trade transparency.', defaultTone: 'defensive', behaviorPattern: 'Questions process and assumptions during evaluation.', commonStrength: 'Becomes cooperative when process is clear.', commonFriction: 'Defensive responses kill momentum quickly.', preferredResponseStyle: 'Walk through process step-by-step.', skillsTested: ['trust', 'relationship', 'listening'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I am open, but I need full clarity on my trade value.' }),
  makeArchetype({ archetypeId: 'skeptical-vague-allergy', archetypeName: 'The Vague Allergy Buyer', category: 'skeptical', corePersonality: 'Immediately reacts against imprecise statements.', defaultTone: 'firm', behaviorPattern: 'Pushes for specifics and commitments.', commonStrength: 'Clear criteria when trust exists.', commonFriction: 'Any uncertainty triggers resistance.', preferredResponseStyle: 'Use concrete language and accurate ranges.', skillsTested: ['trust', 'closing', 'follow_up'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I need concrete answers, not broad sales talk.' }),
  makeArchetype({ archetypeId: 'skeptical-defensive-veteran', archetypeName: 'The Defensive Veteran', category: 'skeptical', corePersonality: 'Experienced buyer who tests consultant composure.', defaultTone: 'guarded', behaviorPattern: 'Challenges statements to verify confidence.', commonStrength: 'Respects calm professionalism.', commonFriction: 'Punishes defensive tone.', preferredResponseStyle: 'Stay calm, factual, and respectful.', skillsTested: ['trust', 'listening', 'relationship'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I have done this before, so keep it straight with me.' }),
  makeArchetype({ archetypeId: 'skeptical-online-quote-checker', archetypeName: 'The Online Quote Checker', category: 'skeptical', corePersonality: 'Cross-checks everything against online offers.', defaultTone: 'skeptical', behaviorPattern: 'Uses online benchmarks to pressure conversation.', commonStrength: 'Decision path exists when value is clarified.', commonFriction: 'Can anchor too early to single number.', preferredResponseStyle: 'Acknowledge market data and frame fit/value.', skillsTested: ['trust', 'closing', 'listening'], humorLevel: 1, difficultyBias: 'hard', exampleOpeningStyle: 'I saw different numbers online, so I need to understand the gap.' }),
  makeArchetype({ archetypeId: 'skeptical-protective-parent', archetypeName: 'The Protective Parent', category: 'skeptical', corePersonality: 'Skeptical because family safety and budget are on the line.', defaultTone: 'guarded-concerned', behaviorPattern: 'Questions reliability, safety, and long-term cost.', commonStrength: 'Opens up when concerns are validated.', commonFriction: 'Rejects any pressure-oriented language.', preferredResponseStyle: 'Lead with empathy and transparent guidance.', skillsTested: ['empathy', 'trust', 'relationship'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'I cannot afford to make the wrong call for my family.' }),

  makeArchetype({ archetypeId: 'budget-payment-maximizer', archetypeName: 'The Payment Maximizer', category: 'budget_focused', corePersonality: 'Focused tightly on monthly payment boundaries.', defaultTone: 'practical', behaviorPattern: 'Keeps returning to payment limits.', commonStrength: 'Clear constraints to plan around.', commonFriction: 'May ignore total value context.', preferredResponseStyle: 'Respect limits and connect payment to fit.', skillsTested: ['closing', 'trust', 'listening'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'I need this to land in a payment range that actually works.' }),
  makeArchetype({ archetypeId: 'budget-long-term-guardian', archetypeName: 'The Long-Term Budget Guardian', category: 'budget_focused', corePersonality: 'Careful planner prioritizing total affordability.', defaultTone: 'cautious', behaviorPattern: 'Asks ownership-cost and reliability questions.', commonStrength: 'Open to long-term framing.', commonFriction: 'Slow to move without clear confidence.', preferredResponseStyle: 'Use patient, transparent ownership math.', skillsTested: ['trust', 'listening', 'follow_up'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'I care about what this costs me over time, not just today.' }),
  makeArchetype({ archetypeId: 'budget-deal-hunter', archetypeName: 'The Deal Hunter', category: 'budget_focused', corePersonality: 'Promotion-focused and opportunity driven.', defaultTone: 'opportunistic', behaviorPattern: 'Asks repeatedly about discounts and incentives.', commonStrength: 'High interest when value is clear.', commonFriction: 'Can reduce conversation to discount-only.', preferredResponseStyle: 'Acknowledge offers while reinforcing value fit.', skillsTested: ['trust', 'closing', 'relationship'], humorLevel: 1, difficultyBias: 'medium', exampleOpeningStyle: 'What current offers can actually move this into range?' }),
  makeArchetype({ archetypeId: 'budget-trade-balancer', archetypeName: 'The Trade Balancer', category: 'budget_focused', corePersonality: 'Balances trade equity with payment concerns.', defaultTone: 'practical', behaviorPattern: 'Moves between trade value and monthly constraints.', commonStrength: 'Clear tradeoff discussion possible.', commonFriction: 'Can feel overwhelmed by too many variables.', preferredResponseStyle: 'Simplify structure and recap tradeoffs.', skillsTested: ['listening', 'trust', 'closing'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I need to understand trade value and payment together before deciding.' }),
  makeArchetype({ archetypeId: 'budget-safety-priority', archetypeName: 'The Safety-on-a-Budget Buyer', category: 'budget_focused', corePersonality: 'Wants safety confidence without stretching finances.', defaultTone: 'cautious', behaviorPattern: 'Prioritizes essentials over extras.', commonStrength: 'Clear priorities when discovered well.', commonFriction: 'Can fear hidden cost creep.', preferredResponseStyle: 'Reassure with transparent essentials-first plan.', skillsTested: ['empathy', 'trust', 'listening'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'I need safe and reliable without breaking the budget.' }),

  makeArchetype({ archetypeId: 'highstakes-time-crunch-exec', archetypeName: 'The Time-Crunch Executive', category: 'high_stakes', corePersonality: 'High urgency with low tolerance for inefficiency.', defaultTone: 'impatient', behaviorPattern: 'Demands concise answers and rapid progress.', commonStrength: 'Will commit quickly if process is clean.', commonFriction: 'Drops trust when flow feels disorganized.', preferredResponseStyle: 'Be concise, structured, and decisive.', skillsTested: ['closing', 'trust', 'follow_up'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I have limited time, so I need this process to stay efficient.' }),
  makeArchetype({ archetypeId: 'highstakes-decision-now', archetypeName: 'The Decision-Now Buyer', category: 'high_stakes', corePersonality: 'Prepared to act today if confidence is earned quickly.', defaultTone: 'focused', behaviorPattern: 'Tests process quality before committing.', commonStrength: 'High conversion potential.', commonFriction: 'Momentum collapses with uncertainty.', preferredResponseStyle: 'Build trust fast and guide clear commitment path.', skillsTested: ['closing', 'trust', 'listening'], humorLevel: 1, difficultyBias: 'hard', exampleOpeningStyle: 'If this makes sense, I am ready to move today.' }),
  makeArchetype({ archetypeId: 'highstakes-status-upgrader', archetypeName: 'The Status Upgrader', category: 'high_stakes', corePersonality: 'Seeking high-stakes upgrade with strong expectations.', defaultTone: 'confident', behaviorPattern: 'Evaluates experience, quality, and confidence signals.', commonStrength: 'Responds to professionalism and clarity.', commonFriction: 'Rejects uncertain or inconsistent guidance.', preferredResponseStyle: 'Lead with poise and transparent expertise.', skillsTested: ['trust', 'relationship', 'closing'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I know what I want in principle, now show me why this is the move.' }),
  makeArchetype({ archetypeId: 'highstakes-business-owner', archetypeName: 'The Business Owner Buyer', category: 'high_stakes', corePersonality: 'Decision-oriented buyer balancing image and utility.', defaultTone: 'direct', behaviorPattern: 'Asks high-impact questions about value and timing.', commonStrength: 'Quick decision path if trust is established.', commonFriction: 'Little patience for unstructured conversation.', preferredResponseStyle: 'Use executive summaries and concrete options.', skillsTested: ['closing', 'follow_up', 'trust'], humorLevel: 1, difficultyBias: 'hard', exampleOpeningStyle: 'I need something that fits my schedule and business image without wasted steps.' }),

  makeArchetype({ archetypeId: 'family-silent-spouse', archetypeName: 'The Silent Spouse', category: 'family_complex', corePersonality: 'Quiet influencer who evaluates every detail silently.', defaultTone: 'reserved', behaviorPattern: 'Speaks little but influences final decision heavily.', commonStrength: 'Will open up when included respectfully.', commonFriction: 'Ignoring them creates hidden resistance.', preferredResponseStyle: 'Invite perspective from all decision-makers.', skillsTested: ['listening', 'relationship', 'trust'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I am mostly listening for now, but I do have concerns.' }),
  makeArchetype({ archetypeId: 'family-multi-driver-home', archetypeName: 'The Multi-Driver Household', category: 'family_complex', corePersonality: 'Balancing different driver needs in one decision.', defaultTone: 'practical', behaviorPattern: 'Moves between multiple stakeholder priorities.', commonStrength: 'Clear needs if guided deliberately.', commonFriction: 'Can feel conflicted and stalled.', preferredResponseStyle: 'Facilitate alignment and summarize tradeoffs.', skillsTested: ['listening', 'follow_up', 'relationship'], humorLevel: 1, difficultyBias: 'hard', exampleOpeningStyle: 'This has to work for more than one person in our house.' }),
  makeArchetype({ archetypeId: 'family-long-commute-parent', archetypeName: 'The Long-Commute Parent', category: 'family_complex', corePersonality: 'Balancing family logistics and heavy commute pressure.', defaultTone: 'stretched', behaviorPattern: 'Prioritizes reliability, comfort, and efficiency.', commonStrength: 'Open to practical solutions.', commonFriction: 'Decision fatigue can appear late.', preferredResponseStyle: 'Keep structure simple and reassuring.', skillsTested: ['empathy', 'listening', 'trust'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'I need this to handle long days and family responsibilities smoothly.' }),

  makeArchetype({ archetypeId: 'emotional-nervous-first-timer', archetypeName: 'The Nervous First-Timer', category: 'emotional', corePersonality: 'Wants help but fears making a costly mistake.', defaultTone: 'anxious', behaviorPattern: 'Requests reassurance and double-checks choices.', commonStrength: 'Open to supportive coaching.', commonFriction: 'Overwhelmed by dense information.', preferredResponseStyle: 'Calm, encouraging, and paced guidance.', skillsTested: ['empathy', 'trust', 'relationship'], humorLevel: 0, difficultyBias: 'easy', exampleOpeningStyle: 'I am excited but nervous, and I do not want to get this wrong.' }),
  makeArchetype({ archetypeId: 'emotional-overwhelmed-parent', archetypeName: 'The Overwhelmed Parent', category: 'emotional', corePersonality: 'Emotionally stretched and short on time.', defaultTone: 'stressed', behaviorPattern: 'Needs clarity and reassurance quickly.', commonStrength: 'Responds strongly to empathy.', commonFriction: 'Shuts down if overloaded.', preferredResponseStyle: 'Simplify and confirm one step at a time.', skillsTested: ['empathy', 'listening', 'follow_up'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'I am trying to solve this fast without making things harder.' }),
  makeArchetype({ archetypeId: 'emotional-service-horror', archetypeName: 'The Service Horror Story', category: 'emotional', corePersonality: 'Carrying strong emotion from past bad service.', defaultTone: 'frustrated', behaviorPattern: 'Tests whether concerns are truly heard.', commonStrength: 'Can recover with genuine acknowledgment.', commonFriction: 'Trust breaks quickly with dismissive tone.', preferredResponseStyle: 'Acknowledge history and commit to transparency.', skillsTested: ['empathy', 'trust', 'relationship'], humorLevel: 0, difficultyBias: 'hard', exampleOpeningStyle: 'I had a bad experience before, so I need to know this is different.' }),
  makeArchetype({ archetypeId: 'emotional-anxious-upgrader', archetypeName: 'The Anxious Upgrader', category: 'emotional', corePersonality: 'Wants an upgrade but fears financial regret.', defaultTone: 'uncertain', behaviorPattern: 'Oscillates between excitement and hesitation.', commonStrength: 'Engaged when reassured.', commonFriction: 'Can retreat from decision late.', preferredResponseStyle: 'Blend reassurance with clear financial clarity.', skillsTested: ['empathy', 'closing', 'trust'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'I want to move up, but I am worried about overreaching.' }),
  makeArchetype({ archetypeId: 'emotional-life-transition', archetypeName: 'The Life-Transition Buyer', category: 'emotional', corePersonality: 'Buying during a major personal transition.', defaultTone: 'sensitive', behaviorPattern: 'Needs emotional safety before practical discussion.', commonStrength: 'Highly responsive to thoughtful empathy.', commonFriction: 'Can disengage if conversation feels transactional.', preferredResponseStyle: 'Lead with empathy, then structure choices.', skillsTested: ['empathy', 'relationship', 'listening'], humorLevel: 0, difficultyBias: 'medium', exampleOpeningStyle: 'A lot is changing right now, so I need this decision to feel stable.' }),
  makeArchetype({ archetypeId: 'emotional-confidence-rebuilder', archetypeName: 'The Confidence Rebuilder', category: 'emotional', corePersonality: 'Needs to rebuild confidence after prior uncertainty.', defaultTone: 'cautious', behaviorPattern: 'Asks for confirmation repeatedly before committing.', commonStrength: 'Trust grows with consistent clarity.', commonFriction: 'Repeated hesitation can stall momentum.', preferredResponseStyle: 'Use consistent checkpoints and gentle commitment cues.', skillsTested: ['trust', 'empathy', 'closing'], humorLevel: 1, difficultyBias: 'medium', exampleOpeningStyle: 'I need to feel sure before I make this move.' }),

  makeArchetype({ archetypeId: 'unusual-dog-photo-customer', archetypeName: 'The Dog Photo Customer', category: 'unusual', corePersonality: 'Shares dog photos and stories while evaluating fit.', defaultTone: 'light', behaviorPattern: 'Builds rapport through personal anecdotes.', commonStrength: 'Strong relationship entry point.', commonFriction: 'Conversation can drift from buying path.', preferredResponseStyle: 'Acknowledge personality and re-anchor to needs.', skillsTested: ['relationship', 'listening', 'follow_up'], humorLevel: 2, difficultyBias: 'medium', exampleOpeningStyle: 'Before anything, do you want to see my dog in the cargo area test?' }),
  makeArchetype({ archetypeId: 'unusual-family-historian', archetypeName: 'The Family Historian', category: 'unusual', corePersonality: 'Frames decisions through family stories and traditions.', defaultTone: 'story-rich', behaviorPattern: 'Long narratives with key hidden priorities.', commonStrength: 'Rich context for discovery.', commonFriction: 'Key decision criteria may be buried.', preferredResponseStyle: 'Listen deeply and summarize patterns.', skillsTested: ['listening', 'relationship', 'trust'], humorLevel: 1, difficultyBias: 'hard', exampleOpeningStyle: 'My family has a long car story, so this choice means a lot.' }),
  makeArchetype({ archetypeId: 'unusual-nickname-collector', archetypeName: 'The Nickname Collector', category: 'unusual', corePersonality: 'Assigns playful nicknames to vehicles instantly.', defaultTone: 'quirky', behaviorPattern: 'Uses humor while still evaluating practical fit.', commonStrength: 'Fast rapport moments.', commonFriction: 'Can dodge direct commitment language.', preferredResponseStyle: 'Use playful tone but keep structured path.', skillsTested: ['relationship', 'closing', 'follow_up'], humorLevel: 3, difficultyBias: 'medium', exampleOpeningStyle: 'This one already has a nickname, now I need to know if it deserves it.' }),
  makeArchetype({ archetypeId: 'unusual-lottery-dreamer-pro', archetypeName: 'The Lottery Dreamer Pro', category: 'unusual', corePersonality: 'Alternates between fantasy and practical constraints.', defaultTone: 'playful', behaviorPattern: 'Tests whether consultant can balance fun with focus.', commonStrength: 'High engagement if paced well.', commonFriction: 'Can break flow with rapid pivots.', preferredResponseStyle: 'Keep light tone and guide toward decision anchors.', skillsTested: ['relationship', 'listening', 'closing'], humorLevel: 3, difficultyBias: 'hard', exampleOpeningStyle: 'I am shopping like I won the lottery, but still on a real budget.' }),
  makeArchetype({ archetypeId: 'unusual-accessory-architect', archetypeName: 'The Accessory Architect', category: 'unusual', corePersonality: 'Design-minded buyer focused on customization journey.', defaultTone: 'creative', behaviorPattern: 'Prioritizes personalization before core specs.', commonStrength: 'Deep engagement with consultant creativity.', commonFriction: 'Can lose track of practical constraints.', preferredResponseStyle: 'Channel creativity into structured options.', skillsTested: ['relationship', 'trust', 'closing'], humorLevel: 2, difficultyBias: 'medium', exampleOpeningStyle: 'I already know how I want this to look, now help me make it smart.' }),
  makeArchetype({ archetypeId: 'unusual-overplanner', archetypeName: 'The Overplanner', category: 'unusual', corePersonality: 'Plans every detail far ahead with unusual edge cases.', defaultTone: 'careful-quirky', behaviorPattern: 'Asks uncommon what-if questions.', commonStrength: 'Open to precise, thoughtful guidance.', commonFriction: 'Can create decision paralysis.', preferredResponseStyle: 'Answer what-ifs, then narrow to top priorities.', skillsTested: ['listening', 'trust', 'follow_up'], humorLevel: 1, difficultyBias: 'hard', exampleOpeningStyle: 'I have a list of scenarios, including some weird ones, if you are game.' }),
];

function hashSeed(value: string): number {
  return [...value].reduce((sum, ch) => ((sum << 5) - sum) + ch.charCodeAt(0), 0) || 1;
}

function pick<T>(items: T[], seed: number): T | null {
  if (!items.length) return null;
  return items[Math.abs(seed) % items.length] ?? null;
}

function normalize(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, '_');
}

export function getFreshUpArchetypeLibrary(): FreshUpArchetype[] {
  return [...FRESH_UP_ARCHETYPE_LIBRARY];
}

export function getFreshUpArchetypeByIdOrName(value: string | null | undefined): FreshUpArchetype | null {
  if (!value) return null;
  const needle = normalize(value);
  return FRESH_UP_ARCHETYPE_LIBRARY.find((item) => (
    normalize(item.archetypeId) === needle || normalize(item.archetypeName) === needle
  )) ?? null;
}

export function getFreshUpArchetypesByCategory(category: FreshUpArchetypeCategory): FreshUpArchetype[] {
  return FRESH_UP_ARCHETYPE_LIBRARY.filter((item) => item.category === category);
}

function mapCustomerTypeToPrimaryCategories(customerType: FreshUpCustomerType): FreshUpArchetypeCategory[] {
  if (customerType === 'Friendly') return ['friendly', 'curious'];
  if (customerType === 'Curious') return ['curious', 'friendly', 'analytical'];
  if (customerType === 'Funny') return ['funny', 'unusual'];
  if (customerType === 'Analytical') return ['analytical', 'skeptical'];
  if (customerType === 'Skeptical') return ['skeptical', 'analytical'];
  if (customerType === 'Budget Focused') return ['budget_focused', 'skeptical'];
  if (customerType === 'High Stakes Buyer') return ['high_stakes', 'skeptical', 'analytical'];
  return ['family_complex', 'emotional'];
}

export function pickFreshUpArchetype(input: {
  customerType: FreshUpCustomerType;
  consultantLevel?: number;
  seedInput: string;
  forcedArchetypeIdOrName?: string;
  allowedCategories?: FreshUpArchetypeCategory[];
}): FreshUpArchetype {
  const forced = getFreshUpArchetypeByIdOrName(input.forcedArchetypeIdOrName);
  if (forced) return forced;

  const seed = hashSeed(input.seedInput);
  const primaryCategories = mapCustomerTypeToPrimaryCategories(input.customerType);
  const levityChance = 18; // Keep humorous/unusual archetypes available at every level.
  const useLevityLane = Math.abs(seed % 100) < levityChance;
  const levityCategories: FreshUpArchetypeCategory[] = ['funny', 'unusual'];
  const categoryPriority = useLevityLane
    ? [...levityCategories, ...primaryCategories]
    : [...primaryCategories, ...levityCategories];

  const filteredCategories = (input.allowedCategories && input.allowedCategories.length > 0)
    ? categoryPriority.filter((category) => input.allowedCategories?.includes(category))
    : categoryPriority;
  const categoryPool = filteredCategories.length > 0 ? filteredCategories : categoryPriority;
  const chosenCategory = categoryPool[Math.abs((seed + (input.consultantLevel ?? 1)) % categoryPool.length)] as FreshUpArchetypeCategory;

  let archetypePool = getFreshUpArchetypesByCategory(chosenCategory);
  if (input.allowedCategories && input.allowedCategories.length > 0) {
    archetypePool = archetypePool.filter((item) => input.allowedCategories?.includes(item.category));
  }
  if (!archetypePool.length) {
    archetypePool = getFreshUpArchetypeLibrary();
  }
  return pick(archetypePool, seed + 41) ?? FRESH_UP_ARCHETYPE_LIBRARY[0];
}
